name: JueJin_Helper

on:
  # push:
  #   branches:
  #     - main
  schedule:
    - cron: "30 21 * * *" # 该时间为UTC时间，比北京时间晚8个小时，每天早上5点半自动执行
  # 也允许这个工作流在github aciton面板中手动触发
  workflow_dispatch:

jobs:
  build:
    # 安装最新的ubuntu系统
    runs-on: ubuntu-latest
    steps:
      # 拉取最新的代码
      - uses: actions/checkout@v2
      # 安装好Nodejs的运行环境
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm ci

  send:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
      - name: Run Project
        env:
          COOKIE: ${{ secrets.COOKIE }}
          USER: ${{ secrets.USER }}
          PASS: ${{ secrets.PASS }}
          TO: ${{ secrets.TO }}
          UID: ${{ secrets.UID }}
          DD_BOT_TOKEN: ${{ secrets.DD_BOT_TOKEN }}
          DD_BOT_SECRET: ${{ secrets.DD_BOT_SECRET }}
          WORKWX_WEBHOOK: ${{ secrets.WORKWX_WEBHOOK }}
        run: npm ci && node index.js
